/**
 * SoundBazz Harmonica & Melodica Product Dataset
 * Source: Harmonica_Comparison_SoundBazz_Detailed_Specifications.pdf
 * 
 * Centralized client-side dataset stored directly in root directory.
 * To add a new harmonica in the future:
 * 1. Add a new product object with a unique key/ID in the `products` map below.
 * 2. Fill in the specification fields using official manufacturer details.
 * 3. Add the image URL and badge properties.
 * 4. The product detail template (product.html) and catalog will automatically handle the rest!
 */

const products = {
    "easttop-et12": {
        id: "easttop-et12",
        name: "Easttop ET12",
        brand: "Easttop",
        brandId: "easttop",
        model: "ET12",
        category: "12-hole chromatic",
        type: "12-hole chromatic",
        key: "C (listing/manufacturer page)",
        holes: "12",
        reeds: "48; phosphor bronze",
        reedMaterial: "Phosphor bronze",
        cover: "ABS",
        comb: "ABS plastic",
        reedPlate: "Brass; 1.2 mm listed for compatible ET12 reed plates",
        mouthpiece: "Integrated plastic/ABS cover & mouthpiece",
        slide: "Chromatic slide; tool-less housing design",
        tuning: "Chromatic / standard solo-style layout",
        range: "3 octaves typical for 12-hole chromatic",
        dimensions: "Exact ET12 dimensions not clearly stated on current official page",
        weight: "Not clearly stated",
        valves: "Wind-saving configuration varies by version; confirm batch",
        price: "₹6,800–₹7,200",
        bestFor: "Students, hobbyists, pop/rock/jazz practice",
        notes: "Modern plastic-bodied Easttop. The official description emphasizes tool-less disassembly/reassembly, fast response and a durable plastic comb.",
        caveat: "Wind-saving valve configuration varies by production version. Confirm exact batch specifications with seller before purchase.",
        dataConfidence: "High for core materials; medium for exact sub-version specifications",
        primarySource: "Easttop official ET12 page",
        img: "https://i.ibb.co/KcSJdZGv/ET-12.jpg",
        badge: "Chromatic",
        badgeColor: "bg-zinc-700"
    },

    "easttop-forerunner-2": {
        id: "easttop-forerunner-2",
        name: "Easttop Forerunner 2.0",
        brand: "Easttop",
        brandId: "easttop",
        model: "T12-48NV2.0",
        category: "12-hole chromatic, valveless",
        type: "12-hole chromatic, valveless",
        key: "C shown in typical listing; multiple keys available",
        holes: "12",
        reeds: "48; phosphor bronze",
        reedMaterial: "Phosphor bronze",
        cover: "Stainless steel, black painted, matte",
        comb: "Transparent ABS",
        reedPlate: "Brass; Easttop's 1.2 mm plate is listed for this model family",
        mouthpiece: "Chrome-plated metal, round-hole style",
        slide: "Updated quieter/smoother slide structure",
        tuning: "Chromatic / solo",
        range: "3 octaves typical",
        dimensions: "Approx. 190 × 40 × 30 mm in marketplace listings",
        weight: "Approx. 240 g in marketplace listings",
        valves: "No valves",
        price: "₹4,500–₹4,800",
        bestFor: "Budget-conscious players specifically wanting a valveless chromatic",
        notes: "The 2.0 version improves the slide structure, cover supports and feel over the original. Valveless construction makes maintenance easy but changes airflow compared with a valved chromatic.",
        caveat: "",
        dataConfidence: "High for model concept/materials; medium for dimensions/weight",
        primarySource: "Easttop official Forerunner 2.0 page",
        img: "https://i.ibb.co/ZRyV72fj/Easttop-Forerunner-2-0.webp",
        badge: "Chromatic",
        badgeColor: "bg-zinc-700"
    },

    "easttop-king-dream": {
        id: "easttop-king-dream",
        name: "Easttop King Dream",
        brand: "Easttop",
        brandId: "easttop",
        model: "T12-48K / T1248K",
        category: "12-hole chromatic",
        type: "12-hole chromatic",
        key: "C",
        holes: "12",
        reeds: "48; phosphor bronze",
        reedMaterial: "Phosphor bronze",
        cover: "Brass, black lacquered",
        comb: "ABS",
        reedPlate: "Brass; 1.2 mm stated by Easttop",
        mouthpiece: "Round-hole mouthpiece",
        slide: "Chromatic slide",
        tuning: "Solo/standard chromatic",
        range: "3 octaves",
        dimensions: "15.8 × 4.2 × 3.0 cm",
        weight: "0.21 kg",
        valves: "Confirm exact valve configuration for supplied version",
        price: "₹5,800–₹6,200",
        bestFor: "Budget-to-midrange general playing",
        notes: "Official King Dream specifications list brass cover/reed plate, ABS comb and phosphor-bronze reeds. Rounded mouth design is intended for comfort.",
        caveat: "Confirm exact valve configuration for the supplied batch with seller prior to purchase.",
        dataConfidence: "High",
        primarySource: "Easttop official T1248K / King Dream page",
        img: "https://i.ibb.co/sd38BYRh/Easttop-King-Dream.jpg",
        badge: "Premium",
        badgeColor: "bg-rose-700"
    },

    "easttop-forerunner": {
        id: "easttop-forerunner",
        name: "Easttop Forerunner",
        brand: "Easttop",
        brandId: "easttop",
        model: "T1248NV",
        category: "12-hole chromatic, valveless",
        type: "12-hole chromatic, valveless",
        key: "C",
        holes: "12",
        reeds: "48; phosphor bronze",
        reedMaterial: "Phosphor bronze",
        cover: "Stainless steel gray",
        comb: "Precision plastic/ABS",
        reedPlate: "Brass; 1.2 mm",
        mouthpiece: "Round mouthpiece",
        slide: "Chromatic slide",
        tuning: "Solo / chromatic",
        range: "3 octaves",
        dimensions: "Approx. 140 × 30 × 40 mm in one marketplace listing; verify batch",
        weight: "Marketplace listings vary; packaged/item data may be 340 g",
        valves: "No valves",
        price: "₹3,700–₹3,900",
        bestFor: "First chromatic on a tight budget",
        notes: "Lower-cost Forerunner design. Its main attraction is the valveless construction and low price.",
        caveat: "",
        dataConfidence: "High for core design; low-medium for dimensions/weight",
        primarySource: "Easttop official T1248NV page",
        img: "https://i.ibb.co/Kj5F5Shh/Easttop-Forerunner.jpg",
        badge: "Chromatic",
        badgeColor: "bg-zinc-700"
    },

    "hohner-260": {
        id: "hohner-260",
        name: "Hohner 260",
        brand: "Hohner",
        brandId: "hohner",
        model: "M26001 / Chromonica 40 (identification caveat)",
        category: "10-hole chromatic (M26001)",
        type: "10-hole chromatic (M26001)",
        key: "C",
        holes: "10",
        reeds: "40; brass",
        reedMaterial: "Brass",
        cover: "Stainless steel",
        comb: "Pearwood",
        reedPlate: "Brass; 1.05 mm",
        mouthpiece: "Nickel-plated metal (M26001 listing)",
        slide: "Straight / short slide action",
        tuning: "Chromatic",
        range: "2.5 octaves",
        dimensions: "Approx. 12.3 cm",
        weight: "Not consistently published",
        valves: "Wind-saving valves",
        price: "₹17,500–₹18,500 (SoundBazz label)",
        bestFor: "Compact traditional Hohner if confirmed as M26001",
        notes: "Classic compact 10-hole valved chromatic with pearwood comb and brass reeds.",
        caveat: "IMPORTANT MODEL IDENTIFICATION NOTE: The SoundBazz screenshot labels this 'Hohner 260 Super Chromonica', but Hohner's model M26001 corresponds to the Chromonica 40: 10 holes / 40 reeds. The 12-hole Super Chromonica is associated with the 270 family. Confirm the seller's exact model number and specifications before purchase.",
        dataConfidence: "High for M26001 specs; low for exact SoundBazz screenshot identity",
        primarySource: "Hohner/retailer technical references; identification caveat",
        img: "https://i.ibb.co/gFrGVHzf/Hohner-260-Super-Chromonica.jpg",
        badge: "Chromatic",
        badgeColor: "bg-zinc-700"
    },

    "hohner-270-deluxe": {
        id: "hohner-270-deluxe",
        name: "Hohner 270 Deluxe",
        brand: "Hohner",
        brandId: "hohner",
        model: "270 Deluxe",
        category: "12-hole chromatic",
        type: "12-hole chromatic",
        key: "C shown; multiple keys exist",
        holes: "12",
        reeds: "48; brass",
        reedMaterial: "Brass",
        cover: "Stainless steel",
        comb: "Double-lacquered pearwood",
        reedPlate: "Brass; 1.2 mm",
        mouthpiece: "Chrome-plated brass, round holes",
        slide: "Straight",
        tuning: "Solo tuning",
        range: "C4–D7; 3 octaves",
        dimensions: "15.5 cm / 6.1 in",
        weight: "Not stated on current official page",
        valves: "Wind-saving valves",
        price: "₹24,000–₹25,000",
        bestFor: "Classical, Bollywood/melodic, jazz, pop and serious long-term learning",
        notes: "Classic professional-grade wooden-comb design. Pearwood and optimized geometry aim for rich tone and improved upper-register response.",
        caveat: "",
        dataConfidence: "High",
        primarySource: "Hohner official 270 Deluxe page",
        img: "https://i.ibb.co/VchNvcfY/Hohner-270-Deluxe.jpg",
        badge: "Professional",
        badgeColor: "bg-amber-700"
    },

    "hohner-cx12": {
        id: "hohner-cx12",
        name: "Hohner CX12",
        brand: "Hohner",
        brandId: "hohner",
        model: "CX12",
        category: "12-hole chromatic",
        type: "12-hole chromatic",
        key: "C and other keys",
        holes: "12",
        reeds: "48; brass",
        reedMaterial: "Brass",
        cover: "ABS integrated cover/mouthpiece",
        comb: "ABS, black",
        reedPlate: "Brass; 1.05 mm",
        mouthpiece: "ABS",
        slide: "Zigzag",
        tuning: "Solo tuning",
        range: "3 octaves",
        dimensions: "16.8 cm / 6.6 in",
        weight: "Approx. 183 g reported by player community; Hohner does not publish weight on current page",
        valves: "Wind-saving valves",
        price: "₹21,000–₹22,000",
        bestFor: "Modern pop/rock/jazz and players who value easy maintenance",
        notes: "Distinctive modern design. The comb/reed-plate assembly slots into the housing for tool-less service; plastic construction is climate-resistant.",
        caveat: "",
        dataConfidence: "High for official specs; medium for weight",
        primarySource: "Hohner official CX12 page",
        img: "https://i.ibb.co/9Hdct2FB/Hohner-Cx12.jpg",
        badge: "Chromatic",
        badgeColor: "bg-zinc-700"
    },

    "hohner-super-64": {
        id: "hohner-super-64",
        name: "Hohner Super 64",
        brand: "Hohner",
        brandId: "hohner",
        model: "64 Chromonica / Super 64",
        category: "16-hole chromatic",
        type: "16-hole chromatic",
        key: "C",
        holes: "16",
        reeds: "64; brass",
        reedMaterial: "Brass",
        cover: "Stainless steel",
        comb: "ABS, black",
        reedPlate: "Brass; 1.05 mm",
        mouthpiece: "Nickel-plated brass",
        slide: "Zigzag",
        tuning: "Solo tuning",
        range: "C3–D7; full 4 octaves",
        dimensions: "19.3 cm / 7.6 in",
        weight: "Not stated on current official page",
        valves: "Wind-saving valves",
        price: "Not shown in screenshot",
        bestFor: "Classical/orchestral-style repertoire and widest standard range",
        notes: "Adds a full lower octave compared with 12-hole models. Useful when repertoire regularly goes below middle C.",
        caveat: "",
        dataConfidence: "High",
        primarySource: "Hohner official 64 Chromonica page",
        img: "https://i.ibb.co/6cCNY83X/Hohner-Super-64.jpg",
        badge: "Pro Series",
        badgeColor: "bg-rose-700"
    },

    "hohner-performer-37": {
        id: "hohner-performer-37",
        name: "Hohner Performer 37",
        brand: "Hohner",
        brandId: "hohner",
        model: "Performer 37 (likely identification)",
        category: "Melodica / keyboard wind instrument",
        type: "Melodica / keyboard wind instrument",
        key: "Keyboard layout",
        holes: "37 keys",
        reeds: "Free reeds; detailed material not stated on current page",
        reedMaterial: "Free reeds (detailed material not stated)",
        cover: "Plastic body",
        comb: "N/A",
        reedPlate: "Internal free-reed system; detailed plate material not stated",
        mouthpiece: "Mouthpiece + extension hose",
        slide: "N/A",
        tuning: "Chromatic keyboard",
        range: "F below middle C to F above",
        dimensions: "56 cm / 22 in",
        weight: "720 g",
        valves: "N/A",
        price: "Not shown in screenshot",
        bestFor: "Melodica players needing broad 37-key range",
        notes: "Pictured instrument is consistent with a Hohner 37-key melodica. Performer 37 features F-to-F range, extension hose, and padded zipper case.",
        caveat: "IMPORTANT MODEL IDENTIFICATION NOTE: SoundBazz screenshot labels this 'Hohner 37 Keys Melodica'. Pictured instrument matches Hohner Performer 37, but exact 37-key sub-model is not printed on screenshot.",
        dataConfidence: "Medium because exact 37-key sub-model is not printed",
        primarySource: "Hohner official Performer 37 page",
        img: "https://i.ibb.co/rG2CT24T/Hohner-37-keys-melodica.jpg",
        badge: "Melodica",
        badgeColor: "bg-blue-700"
    },

    "seydel-deluxe": {
        id: "seydel-deluxe",
        name: "Seydel Deluxe",
        brand: "Seydel",
        brandId: "seydel",
        model: "Chromatic DE LUXE / 51480C",
        category: "12-hole chromatic",
        type: "12-hole chromatic",
        key: "C",
        holes: "12",
        reeds: "48; traditional brass",
        reedMaterial: "Traditional brass",
        cover: "Stainless steel",
        comb: "Brown-tinted acrylic glass",
        reedPlate: "German silver; 1 mm",
        mouthpiece: "Metal, square openings",
        slide: "Straight slide",
        tuning: "Solo tuning",
        range: "3 octaves",
        dimensions: "Approx. 143 × 38 × 27 mm",
        weight: "Not consistently published",
        valves: "Reliable valving",
        price: "₹33,000–₹34,000",
        bestFor: "Players moving into professional-level chromatic playing",
        notes: "Serious German-made 12-hole chromatic with acrylic comb, German-silver reed plates and traditional brass reeds; upgrade path toward DE LUXE STEEL.",
        caveat: "",
        dataConfidence: "High",
        primarySource: "Seydel official DE LUXE page",
        img: "https://i.ibb.co/wZSDDCkM/Chro-De-Luxe-STEEL-Etui-700-72-1.jpg",
        badge: "Chromatic",
        badgeColor: "bg-zinc-700"
    },

    "seydel-saxony": {
        id: "seydel-saxony",
        name: "Seydel Saxony",
        brand: "Seydel",
        brandId: "seydel",
        model: "SAXONY Chromatic 52480C",
        category: "12-hole chromatic",
        type: "12-hole chromatic",
        key: "C",
        holes: "12",
        reeds: "48; stainless steel, fully valved",
        reedMaterial: "Stainless steel",
        cover: "Stainless steel",
        comb: "CNC-machined aluminium, coated",
        reedPlate: "German silver; 1 mm",
        mouthpiece: "Chromed metal, round holes",
        slide: "German-silver slider; optimized airtight design",
        tuning: "Solo straight",
        range: "3 octaves",
        dimensions: "158 × 36 × 30 mm",
        weight: "250 g manufacturer technical data; some pages list 272 g",
        valves: "Fully valved",
        price: "₹39,000–₹41,000",
        bestFor: "Professional/serious players prioritizing durability and stainless-steel reeds",
        notes: "Stainless-steel reeds are designed for durability and tuning stability under heavy use. German-silver plates and aluminium comb support airtightness and response.",
        caveat: "",
        dataConfidence: "High; published weight varies by manufacturer page",
        primarySource: "Seydel official SAXONY page",
        img: "https://i.ibb.co/xKrr5rLR/Saxony.png",
        badge: "Chromatic",
        badgeColor: "bg-zinc-700"
    },

    "seydel-non-slider": {
        id: "seydel-non-slider",
        name: "Seydel Non-Slider Chromatic",
        brand: "Seydel",
        brandId: "seydel",
        model: "NONSLIDER Chromatic 54481C",
        category: "12-hole chromatic, no slider",
        type: "12-hole chromatic, no slider",
        key: "C (also other keys)",
        holes: "12 × 2 mouthpiece rows",
        reeds: "48; stainless steel",
        reedMaterial: "Stainless steel",
        cover: "Stainless steel",
        comb: "CNC-milled orange acrylic glass",
        reedPlate: "German silver; 1 mm",
        mouthpiece: "12 × 2-hole double-row, silvered, half-moon",
        slide: "None",
        tuning: "Solo; Orchestra option exists",
        range: "3 octaves",
        dimensions: "143 × 38 × 27 mm",
        weight: "196 g",
        valves: "No valves for standard versions",
        price: "Not shown in screenshot",
        bestFor: "Players who want chromatic notes with a direct, diatonic-like feel",
        notes: "Uses upper/lower mouthpiece rows instead of a traditional slide. Designed for direct response, low air consumption and no slider/valve maintenance.",
        caveat: "",
        dataConfidence: "High",
        primarySource: "Seydel official NONSLIDER page",
        img: "https://i.ibb.co/PzQrv5sZ/Seydel-Non-slider-chromatic.jpg",
        badge: "Chromatic",
        badgeColor: "bg-zinc-700"
    },

    "seydel-symphony": {
        id: "seydel-symphony",
        name: "Seydel Symphony",
        brand: "Seydel",
        brandId: "seydel",
        model: "SYMPHONY 48 55480C",
        category: "12-hole professional chromatic",
        type: "12-hole professional chromatic",
        key: "C / C Orchestra",
        holes: "12",
        reeds: "48; polished stainless steel, fully valved",
        reedMaterial: "Polished stainless steel",
        cover: "Aluminium die-cast, powder coated",
        comb: "CNC-milled black-anodized aluminium",
        reedPlate: "German silver; 1 mm",
        mouthpiece: "Silver-coated, half-moon, round holes",
        slide: "Magnetic stainless-steel slider",
        tuning: "Solo – cross",
        range: "3 octaves",
        dimensions: "154 × 50 × 38 mm",
        weight: "307 g",
        valves: "Fully valved",
        price: "Not shown in screenshot",
        bestFor: "Professional performance and studio work",
        notes: "Premium design with magnetic slider system intended to remove spring-related failure points and provide smooth low-friction action.",
        caveat: "",
        dataConfidence: "High",
        primarySource: "Seydel official SYMPHONY 48 page",
        img: "https://i.ibb.co/Xf2B4ft4/Seydey-Symphony.jpg",
        badge: "Premium",
        badgeColor: "bg-rose-700"
    },

    "suzuki-scx48": {
        id: "suzuki-scx48",
        name: "Suzuki SCX48",
        brand: "Suzuki",
        brandId: "suzuki",
        model: "SCX-48",
        category: "12-hole chromatic",
        type: "12-hole chromatic",
        key: "C",
        holes: "12",
        reeds: "48; Suzuki reed system",
        reedMaterial: "Suzuki reed system",
        cover: "Brass + chrome plating",
        comb: "ABS",
        reedPlate: "Replacement reed plates available; alloy/thickness not stated on official page",
        mouthpiece: "Metal/plated mouthpiece assembly",
        slide: "Long stroke, cross alignment",
        tuning: "Slide chromatic",
        range: "C4–D7; 3 octaves",
        dimensions: "158 × 45 × 30 mm",
        weight: "235 g",
        valves: "Internal wind-saving system",
        price: "Not shown in screenshot",
        bestFor: "Excellent all-round 12-hole modern chromatic",
        notes: "Suzuki emphasizes airtight processing, quick response and a light, spreading sound in the SCX line.",
        caveat: "",
        dataConfidence: "High",
        primarySource: "Suzuki official SCX-48 page",
        img: "https://i.ibb.co/q3bG5bdt/Suzuki-Scx48.jpg",
        badge: "Chromatic",
        badgeColor: "bg-zinc-700"
    },

    "suzuki-scx64": {
        id: "suzuki-scx64",
        name: "Suzuki SCX64",
        brand: "Suzuki",
        brandId: "suzuki",
        model: "SCX-64",
        category: "16-hole chromatic",
        type: "16-hole chromatic",
        key: "C",
        holes: "16",
        reeds: "64; Suzuki reed system",
        reedMaterial: "Suzuki reed system",
        cover: "Brass + chrome plating",
        comb: "ABS",
        reedPlate: "Replacement reed plates available; alloy/thickness not stated on official page",
        mouthpiece: "Metal/plated mouthpiece assembly",
        slide: "Long stroke, cross alignment",
        tuning: "Slide chromatic",
        range: "C3–D7; 4 octaves",
        dimensions: "195 × 45 × 30 mm",
        weight: "290 g",
        valves: "Internal wind-saving system",
        price: "₹19,000–₹19,500",
        bestFor: "Players wanting four octaves without a flagship-weight instrument",
        notes: "Four-octave SCX with lower register while retaining lightweight ABS body and long-stroke slide.",
        caveat: "",
        dataConfidence: "High",
        primarySource: "Suzuki official SCX-64 page",
        img: "https://i.ibb.co/zhVg6Zpm/4333suzuki-scx-64-chromatic-harmonica-2.jpg",
        badge: "Chromatic",
        badgeColor: "bg-zinc-700"
    },

    "suzuki-m32c": {
        id: "suzuki-m32c",
        name: "Suzuki M-32C",
        brand: "Suzuki",
        brandId: "suzuki",
        model: "M-32C",
        category: "32-key melodica / Melodion",
        type: "32-key melodica / Melodion",
        key: "Keyboard layout",
        holes: "32 keys",
        reeds: "Phosphor bronze free reeds",
        reedMaterial: "Phosphor bronze free reeds",
        cover: "Steel",
        comb: "N/A",
        reedPlate: "Internal free-reed plate; detailed thickness not stated",
        mouthpiece: "Short MP-121 + flexible MP-113",
        slide: "N/A",
        tuning: "Chromatic keyboard",
        range: "F–C3",
        dimensions: "430 × 100 × 50 mm body; 470 × 150 × 75 mm case",
        weight: "765 g body; 546 g current official case figure",
        valves: "N/A",
        price: "Not shown in screenshot",
        bestFor: "Beginner/intermediate melodica and school/general playing",
        notes: "Long-running educational model with steel cover and phosphor-bronze reeds.",
        caveat: "",
        dataConfidence: "High",
        primarySource: "Suzuki official M-32C page",
        img: "https://i.ibb.co/FkQkrGxz/Suzuki-32-keys-Melodica.jpg",
        badge: "Melodica",
        badgeColor: "bg-blue-700"
    },

    "jdr-gm-0648": {
        id: "jdr-gm-0648",
        name: "JDR GM-0648",
        brand: "JDR",
        brandId: "jdr",
        model: "GM0648 / GM-0648",
        category: "12-hole chromatic",
        type: "12-hole chromatic",
        key: "C/C6",
        holes: "12",
        reeds: "Phosphor bronze",
        reedMaterial: "Phosphor bronze",
        cover: "Sprayed copper / thickened brass cover (JDR wording varies)",
        comb: "Waterproof ABS",
        reedPlate: "Brass; 1.2 mm",
        mouthpiece: "Chrome-plated copper",
        slide: "Zigzag",
        tuning: "Standard chromatic",
        range: "3 octaves typical",
        dimensions: "6.25 × 1.18 × 1.77 in (≈158.8 × 30.0 × 45.0 mm)",
        weight: "0.56 lb on main page; JDR page contains conflicting weight snippets",
        valves: "Durable valves",
        price: "₹9,000–₹9,500",
        bestFor: "Strong midrange valved chromatic for beginners and advancing players",
        notes: "This is the model represented by SoundBazz specification image: sprayed copper cover, ABS comb, phosphor bronze reed, 1.2 mm brass reed plates, chrome-plated copper mouthpiece, C/C6 and zigzag slide.",
        caveat: "Sound Bazz is the exclusive authorized distributor and seller of JDR brand harmonicas in India. Note: JDR official page contains slightly varying weight and cover material wording.",
        dataConfidence: "High for core materials; medium for weight/cover wording",
        primarySource: "JDR official GM0648 page",
        img: "https://i.ibb.co/yFXsWgj2/71pdz-Y8-Vi9-L-AC-UF1000-1000-QL80.jpg",
        badge: "Chromatic",
        badgeColor: "bg-zinc-700"
    },

    "jdr-trochilus": {
        id: "jdr-trochilus",
        name: "JDR Trochilus",
        brand: "JDR",
        brandId: "jdr",
        model: "Trochilus 10-hole",
        category: "10-hole hybrid chromatic / valveless",
        type: "10-hole hybrid chromatic / valveless",
        key: "C shown; other keys available",
        holes: "10",
        reeds: "Phosphor bronze",
        reedMaterial: "Phosphor bronze",
        cover: "0.5 mm chrome-plated copper",
        comb: "ABS resin, trapezoid body",
        reedPlate: "Electroplated brass / spring plate",
        mouthpiece: "Chrome-plated copper",
        slide: "Dual-tuning slider; no valves",
        tuning: "Blues/Richter, Pop or Chromatic/Solo depending version",
        range: "3 octaves in Blues/Richter; 2.5 octaves in Solo",
        dimensions: "5.27 × 0.78 × 1.22 in (≈133.9 × 19.8 × 31.0 mm)",
        weight: "0.28 lb (≈127 g)",
        valves: "None",
        price: "₹10,500–₹11,000",
        bestFor: "Players coming from blues/diatonic harmonica who want chromatic capability in a compact form",
        notes: "Not a conventional 12-hole chromatic. Its unique 10-hole layout aims to retain diatonic-style bending while the slider adds semitone access.",
        caveat: "Sound Bazz is the exclusive authorized distributor and seller of JDR brand harmonicas in India.",
        dataConfidence: "High",
        primarySource: "JDR official Trochilus page",
        img: "https://i.ibb.co/4wLTvTgZ/Whats-App-Image-2026-08-09-at-1-15-43-PM.jpg",
        badge: "Chromatic",
        badgeColor: "bg-zinc-700"
    },

    // Accessories
    "harmonica-bag": {
        id: "harmonica-bag",
        name: "Harmonica Bag",
        brand: "SoundBazz Special",
        brandId: "special",
        model: "Harmonica Soft Bag",
        category: "Accessory",
        type: "Protective Carrying Bag",
        key: "N/A",
        holes: "N/A",
        reeds: "N/A",
        reedMaterial: "N/A",
        cover: "Durable Fabric Padded Bag",
        comb: "N/A",
        reedPlate: "N/A",
        mouthpiece: "N/A",
        slide: "N/A",
        tuning: "N/A",
        range: "N/A",
        dimensions: "Standard Harmonica Size",
        weight: "Lightweight",
        valves: "N/A",
        price: "Contact for Price",
        bestFor: "Protecting harmonicas during storage & travel",
        notes: "High-quality padded protective bag for harmonicas.",
        caveat: "",
        dataConfidence: "High",
        primarySource: "SoundBazz Catalog",
        img: "https://i.ibb.co/B2yhV1Xs/Harmonica-bag.jpg",
        badge: "Accessory",
        badgeColor: "bg-emerald-700"
    },

    "harmonica-case": {
        id: "harmonica-case",
        name: "Harmonica Case",
        brand: "SoundBazz Special",
        brandId: "special",
        model: "Harmonica Hard Shell Case",
        category: "Accessory",
        type: "Hard Case",
        key: "N/A",
        holes: "N/A",
        reeds: "N/A",
        reedMaterial: "N/A",
        cover: "Hard Shell Exterior",
        comb: "N/A",
        reedPlate: "N/A",
        mouthpiece: "N/A",
        slide: "N/A",
        tuning: "N/A",
        range: "N/A",
        dimensions: "Fits Standard Chromatic / Diatonic",
        weight: "Protective",
        valves: "N/A",
        price: "Contact for Price",
        bestFor: "Maximum protection against impact & dust",
        notes: "Sturdy hard shell case providing superior protection for your valuable instruments.",
        caveat: "",
        dataConfidence: "High",
        primarySource: "SoundBazz Catalog",
        img: "https://i.ibb.co/TBWZ882B/Harmonica-case.jpg",
        badge: "Accessory",
        badgeColor: "bg-emerald-700"
    },

    "leather-harmonica-case": {
        id: "leather-harmonica-case",
        name: "Leather Harmonica Case",
        brand: "SoundBazz Special",
        brandId: "special",
        model: "Leather Executive Case",
        category: "Accessory",
        type: "Premium Leather Case",
        key: "N/A",
        holes: "N/A",
        reeds: "N/A",
        reedMaterial: "N/A",
        cover: "Genuine Leather Finish",
        comb: "N/A",
        reedPlate: "N/A",
        mouthpiece: "N/A",
        slide: "N/A",
        tuning: "N/A",
        range: "N/A",
        dimensions: "Fits Standard Chromatic",
        weight: "Premium Feel",
        valves: "N/A",
        price: "Contact for Price",
        bestFor: "Professional performers seeking elegant presentation & protection",
        notes: "Premium leather case crafted for durability and high-end aesthetic appeal.",
        caveat: "",
        dataConfidence: "High",
        primarySource: "SoundBazz Catalog",
        img: "https://i.ibb.co/q32fBv0z/leather-harmonica-case.jpg",
        badge: "Accessory",
        badgeColor: "bg-emerald-700"
    }
};

// Aliases for alternate URL IDs
products["hohner-37-keys-melodica"] = products["hohner-performer-37"];
products["suzuki-32-keys-melodica"] = products["suzuki-m32c"];
products["hohner-260-super-chromonica"] = products["hohner-260"];
products["trochilus"] = products["jdr-trochilus"];

/**
 * Retrieve product by ID safely. Returns null if not found.
 */
function getProductById(id) {
    if (!id) return null;
    const cleanId = id.trim().toLowerCase();
    return products[cleanId] || null;
}

/**
 * Get related products based on brand, category, or hole count.
 */
function getRelatedProducts(productId, count = 4) {
    const current = getProductById(productId);
    if (!current) return [];

    const currentKey = current.id;
    const allItems = Object.values(products).filter(p => p.id !== currentKey && !p.id.includes("keys-melodica") && p.id !== "trochilus" && p.id !== "hohner-260-super-chromonica");
    
    // De-duplicate array by ID
    const uniqueItems = Array.from(new Map(allItems.map(item => [item.id, item])).values());

    // Priority 1: Same brand
    const sameBrand = uniqueItems.filter(p => p.brandId === current.brandId);
    
    // Priority 2: Same type/category (e.g. chromatic)
    const sameType = uniqueItems.filter(p => p.brandId !== current.brandId && p.badge === current.badge);

    // Priority 3: Rest
    const rest = uniqueItems.filter(p => p.brandId !== current.brandId && p.badge !== current.badge);

    const pool = [...sameBrand, ...sameType, ...rest];
    return pool.slice(0, count);
}
